/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matriculaAcademica.ui;

import com.mycompany.avila.matricula.logica.Periodo;
import com.mycompany.avila.matricula.logica.Universidad;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian D. Avila N.
 */
public class RegistroPeriodosUI extends javax.swing.JFrame {

    private Universidad universidad;

    /**
     * Creates new form RegistroPeriodosUI
     */
    public RegistroPeriodosUI() {
        initComponents();
        this.universidad = new Universidad(1957500, "Universidad del Valle", "Zamorano", null);
        jButtonCancelar.addActionListener(new CancelListener());
        jButtonGuardar.addActionListener(new SaveListener());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txfInicioMesPeriodo = new javax.swing.JTextField();
        txfInicioAño = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txfFinMesPeriodo = new javax.swing.JTextField();
        txfFinAño = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Creacion de Periodos Academicos");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Creación de Periodos Académicos");

        jLabel1.setText("Inicia :");

        jLabel3.setText("Finaliza :");

        txfFinAño.setEditable(false);
        txfFinAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfFinAñoActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfInicioMesPeriodo)
                                    .addComponent(txfFinMesPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfFinAño, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(txfInicioAño)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfInicioMesPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfInicioAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfFinMesPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfFinAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonCancelar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void txfFinAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfFinAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfFinAñoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txfFinAño;
    private javax.swing.JTextField txfFinMesPeriodo;
    private javax.swing.JTextField txfInicioAño;
    private javax.swing.JTextField txfInicioMesPeriodo;
    // End of variables declaration//GEN-END:variables

    //Permite borrar toda la información ingresada en los campos de texto solicitados
    public class CancelListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {

            txfInicioMesPeriodo.setText("");
            txfInicioAño.setText("");
            txfFinMesPeriodo.setText("");
            txfFinAño.setText("");

        }

    }

    public class SaveListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {

            // 1. Obtener la información de los componentes gráficos
            //String txt = txfInitMonth.getText();
            String inicioMesPeriodo = txfInicioMesPeriodo.getText();
            short inicioAño = Short.parseShort(txfInicioAño.getText());
            String finMesPeriodo = txfFinMesPeriodo.getText();
            short finAño = Short.parseShort(txfFinAño.getText());

            // 2. Crear el objeto (con la información)
            //Periodo periodo = new Periodo(....);
            Periodo periodo = new Periodo(inicioMesPeriodo, finMesPeriodo, inicioAño, finAño);

            // 3. Agregar el objeto a la universidad
            //or 
            universidad.add(periodo);
            // 4. Mostrar un mensaje que indique que el periodo fue creado
            //    y agregado a la Universidad
            JOptionPane.showMessageDialog(RegistroPeriodosUI.this, "Información almacenada satisfactoriamente, PERIODO agregado.");
        }

    }

}
